# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Apache
      run: sudo apt-get update && sudo apt-get install -y apache2

    - name: Start Apache
      run: sudo systemctl start apache2

    - name: Check Apache status
      run: sudo systemctl status apache2

    - name: Display Apache default page (optional)
      run: curl http://localhost
